apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Merge
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: todo-app/postgres-secret
      property: DB_PASSWORD
