# ─── Allow frontend to talk to backend only ──────────
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - ports:
    - port: 3001
    to:
    - podSelector:
        matchLabels:
          app: backend
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
# ─── Allow backend to talk to postgres only ──────────
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
    ports:
    - port: 3001
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - port: 3001
  egress:
  - ports:
    - port: 5432
    to:
    - podSelector:
        matchLabels:
          app: postgres
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
# ─── Allow only backend to talk to postgres ──────────
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend
    ports:
    - port: 5432
